### ISSUE TITLE
Developer tools no longer at URL provided in README

### ISSUE THREAD

**Issue by objectiveSee** [dhleong/reverb#2]
Any idea where to find dev tools now?

**Comment by dhleong** [comment]
The chrome dev tools? There's no url provided for that.... You should be
able to pull them up from the options menu.

**Comment by objectiveSee** [comment]
Thanks! Thought there was a "developer tools" section on the Echo webpage. Got my :cookie: now

**Comment by dhleong** [comment]
If only there was! ;)

**Comment by objectiveSee** [comment]
@dhleong I still don't get how this is useful for developing Echo functionality... but I know it is. Can you shed some light on what your development flow is? I have it all up and running and can see commands coming in that I am speaking (which is awesome).  I am using `grunt-aws-lambda` for getting my code on Echo for testing which isn't too bad.

**Comment by dhleong** [comment]
I don't actively use this because pushes don't wake the machine I run local server stuff on, but this would not be used with Lambda. 

You would use this with manual text parsing to have custom Echo commands that don't require the "Ask app to do bla" syntax, though you would have to add "cancel" or "stop" to the end to prevent the default functionality. Basically I developed it before the ASK stuff was finalized. 

If you just want to use ASK, I also wrote a library for that: https://github.com/dhleong/expressive
